-- 标签表：同一用户下唯一




CREATE TABLE IF NOT EXISTS tags (
  id        BIGINT PRIMARY KEY AUTO_INCREMENT,
  owner_id  BIGINT NOT NULL,
  name      VARCHAR(64) NOT NULL,
  kind      ENUM('user','exif','system') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_owner_name (owner_id, name),
  KEY idx_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 关联表：多对多
DROP TABLE IF EXISTS image_tags;
CREATE TABLE image_tags (
  image_id INT    NOT NULL,
  tag_id   BIGINT NOT NULL,
  PRIMARY KEY (image_id, tag_id),
  KEY idx_tag (tag_id),
  CONSTRAINT fk_it_image FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE,
  CONSTRAINT fk_it_tag   FOREIGN KEY (tag_id)   REFERENCES tags(id)   ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- ===== 兼容旧版 MySQL 的“条件加列”写法（逐列判断+动态 ALTER） =====
-- 注意：stored_path 用 NOT NULL DEFAULT ''，避免旧库里已有数据时报错
SET @tbl := 'images';

-- stored_path
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='stored_path');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN stored_path VARCHAR(255) NOT NULL DEFAULT '''';', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- mime_type
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='mime_type');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN mime_type VARCHAR(64) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- size_bytes
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='size_bytes');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN size_bytes BIGINT NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- width
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='width');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN width INT NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- height
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='height');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN height INT NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- sha256
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='sha256');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN sha256 CHAR(64) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- camera_make
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='camera_make');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN camera_make VARCHAR(64) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- camera_model
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='camera_model');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN camera_model VARCHAR(64) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- gps_lat
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='gps_lat');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN gps_lat DECIMAL(10,7) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- gps_lng
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='gps_lng');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN gps_lng DECIMAL(10,7) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- taken_at
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='taken_at');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN taken_at DATETIME NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- title
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='title');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN title VARCHAR(128) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- description
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='description');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN description TEXT NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- thumb_path
SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=@tbl AND COLUMN_NAME='thumb_path');
SET @sql := IF(@x=0, 'ALTER TABLE images ADD COLUMN thumb_path VARCHAR(255) NULL;', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ===== 索引（存在则不重复创建） =====
-- uniq_user_hash (owner_id, sha256)
SET @ix := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
            WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='images' AND INDEX_NAME='uniq_user_hash');
SET @sql := IF(@ix=0, 'ALTER TABLE images ADD UNIQUE KEY uniq_user_hash (owner_id, sha256);', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- idx_owner_taken (owner_id, taken_at)
SET @ix := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
            WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='images' AND INDEX_NAME='idx_owner_taken');
SET @sql := IF(@ix=0, 'ALTER TABLE images ADD KEY idx_owner_taken (owner_id, taken_at);', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;




-- 这边定义更改了